### ISSUE TITLE
普通机构注册时，上传机构照片报错

### ISSUE THREAD

**Issue by JcobCN** [WeBankBlockchain/DDCMS#4]
![image](https://github.com/WeBankBlockchain/DDCMS/assets/19268110/a8341293-ed27-4cae-8160-f39d6aa1d0ea)
![image](https://github.com/WeBankBlockchain/DDCMS/assets/19268110/d220ee9f-f352-4a0a-9761-3930ae104f12)
![image](https://github.com/WeBankBlockchain/DDCMS/assets/19268110/7ccfe40e-2adc-4765-861a-c692da997bd3)

**Comment by dalaocu** [comment]
#https://github.com/WeBankBlockchain/DDCMS-Service/commit/23a1b607e0a1b19dd85a7358a7982dd2c3d8832a
#https://github.com/WeBankBlockchain/DDCMS-Service/commit/e07c8ff31e2556066078a510d3381543847ff61e
